export const JOB_REGISTER = 'JOB_REGISTER'
export const JOB_SUCCESS = 'JOB_SUCCESS'
export const JOB_FAILURE = 'JOB_FAILURE'

export const APPLICANT_REGISTER = 'APPLICANT_REGISTER'
export const APPLICANT_SUCCESS = 'APPLICANT_SUCCESS'
export const APPLICANT_FAILURE = 'APPLICANT_FAILURE'
