export const ADD_JOB = 'ADD_JOB'
export const JOBS_LOADING = 'JOBS_LOADING'
export const JOBS_FAILED = 'JOBS_FAILED'

export const ADD_APPLICANT = 'ADD_APPLICANT'
export const APPLICANTS_LOADING = 'APPLICANTS_LOADING'
export const APPLICANTS_FAILED = 'APPLICANTS_FAILED'
