export const ADD_JOB = 'ADD_JOB'
export const JOBS_LOADING = 'JOBS_LOADING'
export const JOBS_FAILED = 'JOBS_FAILED'

export const ADD_APPLICANT = 'ADD_APPLICANT'
export const APPLICANTS_LOADING = 'APPLICANTS_LOADING'
export const APPLICANTS_FAILED = 'APPLICANTS_FAILED'

export const REGISTER_REQUEST = 'REGISTER_REQUEST'
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS'
export const REGISTER_FAILURE = 'REGISTER_FAILURE'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
export const LOGIN_FAILURE = 'LOGIN_FAILURE'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'
export const LOGOUT_FAILURE = 'LOGOUT_FAILURE'
